language: python

CIBW_TEST_REQUIRES: pytest
CIBW_BEFORE_BUILD: pip install -r requirements.txt
CIBW_TEST_COMMAND: pytest {project}/tests

jobs:
  include:
    # perform a linux build
    # - services: docker
    # and a mac build
    # - os: osx
    #   language: shell
    #   before_install:
    #     - brew install libomp
    #     - export PATH="/usr/local/bin:/usr/local/opt/llvm/bin:$PATH"
    #     - ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
    # and a windows build
    - os: windows
     language: shell
     before_install:
       - choco install python3
       - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

env:
  global:
    - TWINE_USERNAME=joerick
      # Note: TWINE_PASSWORD is set in Travis settings
    - CC="gcc"  

install:
  - python -m pip install twine cibuildwheel==1.1.0

script:
  # build the wheels, put them into './wheelhouse'
  - python -m cibuildwheel --output-dir wheelhouse

after_success:
  # if the release was tagged, upload them to PyPI
  - if [[ $TRAVIS_TAG ]]; then python -m twine upload wheelhouse/*.whl; fi