language: python
python: "3.7"

env:
  global:
    - TWINE_USERNAME=UPDATEME
      # Note: TWINE_PASSWORD is set in Travis settings
    - CC="gcc"  

    # skip 32 bit builds and python 2.7 builds
    - CIBW_SKIP="cp27-* *-win32 *-manylinux_i686"

jobs:
  include:
    # perform a linux build
    - services: docker
      language: shell
      before_install:
        - pip install -r requirements.txt
        - pip install -e .
        - pytest tests
        - pip uninstall -y matrixprofile-ts
    # and a mac build
    # gcc is already installed just have to link it and install libomp
    - os: osx
      language: shell
      before_install:
        - brew install libomp
        - export PATH="/usr/local/bin:$PATH"
        - ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc
        - pip install -r requirements.txt
        - pip install -e .
        - pytest tests
        - pip uninstall -y matrixprofile-ts
    # and a windows build
    - os: windows
      language: shell
      before_install:
        - choco install python3
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
        - pip install -r requirements.txt
        - pip install -e .
        - pytest tests
        - pip uninstall -y matrixprofile-ts

install:
  - python -m pip install twine cibuildwheel==1.1.0

script:
  # build the wheels, put them into './wheelhouse'
  - python -m cibuildwheel --output-dir wheelhouse

after_success:
  # if the release was tagged, upload them to PyPI
  - ls ./wheelhouse/*.whl
  - if [[ $TRAVIS_TAG ]]; then python -m twine upload wheelhouse/*.whl; fi